'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SchedulerReportPreviewTest

    Public Partial Class Register

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' lblUserName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lblUserName As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' tbUserName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected tbUserName As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' lblEmail control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lblEmail As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' tbEmail control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected tbEmail As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' lblPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lblPassword As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' tbPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected tbPassword As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' lblConfirmPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lblConfirmPassword As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' tbConfirmPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected tbConfirmPassword As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' btnCreateUser control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnCreateUser As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
