'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace SchedulerReportPreviewTest


    Partial Public Class Calendar

        ''' <summary>
        ''' DateNavigator control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DateNavigator As Global.DevExpress.Web.ASPxScheduler.ASPxDateNavigator

        ''' <summary>
        ''' Scheduler control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Scheduler As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

        ''' <summary>
        ''' AppointmentDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AppointmentDataSource As Global.System.Web.UI.WebControls.SqlDataSource

        ''' <summary>
        ''' ResourceDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ResourceDataSource As Global.System.Web.UI.WebControls.SqlDataSource

        ''' <summary>
        ''' ASPxPopupControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' ASPxCallbackPanel1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxCallbackPanel1 As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' PreviewPanel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PreviewPanel As Global.System.Web.UI.WebControls.Panel

        ''' <summary>
        ''' ASPxSchedulerControlPrintAdapter1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxSchedulerControlPrintAdapter1 As Global.DevExpress.Web.ASPxScheduler.Reporting.ASPxSchedulerControlPrintAdapter
    End Class
End Namespace
