'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SchedulerReportPreviewTest

    Public Partial Class _Default

        ''' <summary>
        ''' MailFilter control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MailFilter As Global.DevExpress.Web.ASPxTreeView

        ''' <summary>
        ''' ContentSplitter control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ContentSplitter As Global.DevExpress.Web.ASPxSplitter

        ''' <summary>
        ''' MessageListPanel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MessageListPanel As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' MessagesGrid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MessagesGrid As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' MessagesDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MessagesDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
