'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SchedulerReportPreviewTest

    Public Partial Class Main

        ''' <summary>
        ''' ASPxSplitter1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxSplitter1 As Global.DevExpress.Web.ASPxSplitter

        ''' <summary>
        ''' LeftSplitter control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LeftSplitter As Global.DevExpress.Web.ASPxSplitter

        ''' <summary>
        ''' Left control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Left As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' MenuCorner control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MenuCorner As Global.DevExpress.Web.ASPxMenu

        ''' <summary>
        ''' Content control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Content As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
