'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace DXApplication1
	Partial Public Class ChangePassword

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' lblCurrentPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblCurrentPassword As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' tbCurrentPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbCurrentPassword As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' lblPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblPassword As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' tbPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbPassword As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' lblConfirmPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblConfirmPassword As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' tbConfirmPassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbConfirmPassword As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' btnChangePassword control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnChangePassword As Global.DevExpress.Web.ASPxEditors.ASPxButton
	End Class
End Namespace